# Generated by Django 5.1.5 on 2025-06-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('date', models.DateField(verbose_name='Дата')),
                ('min_temperature', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Минимальная температура')),
                ('max_temperature', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Максимальная температура')),
            ],
            options={
                'verbose_name': 'Прогноз',
                'verbose_name_plural': 'Прогнозы',
                'unique_together': {('city', 'date')},
            },
        ),
    ]
