# Generated by Django 5.1.5 on 2025-06-09 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='forecastmodel',
            unique_together=set(),
        ),
    ]
